### ISSUE TITLE
Add Noted.lol under Websites/Blogs

### ISSUE THREAD

**Issue by ItsNoted** [mikeroyal/Self-Hosting-Guide#198]
Hey there! Just requesting to have [Noted](https://noted.lol) added to the Websites/Blogs section. I've referenced this guide multiple times across my network. Really great contribution to the community!

**Comment by mikeroyal** [comment]
Will add thank you for the suggestion.

**Comment by mikeroyal** [comment]
Okay, it's been added to the Tutorials & Resources section.
