### ISSUE TITLE
Docker Swarm seems to refer to the deprecated Classic Swarm

### ISSUE THREAD

**Issue by s4ke** [mikeroyal/Self-Hosting-Guide#253]
> [Docker Swarm](https://docs.docker.com/engine/swarm/) is a Docker-native clustering system swarm is a simple tool which controls a cluster of Docker hosts and exposes it as a single "virtual" host.

This seems to refer to the old classic swarm. The newer swarm mode does not expose things as a "virtual" host, but instead uses an approach that is more similar to Kubernetes in terms of operating mode.

see https://github.com/docker-archive/classicswarm where the quote comes from "Docker Swarm "Classic" is native clustering for Docker. It turns a pool of Docker hosts into a single, virtual host."

Docker Swarm Mode (which is what people usually mean when they talk about Docker Swarm nowadays) is part of Docker and is built on top of swarmkit https://github.com/moby/swarmkit

**Comment by mikeroyal** [comment]
Yes, it seems you're right feel free to PR if you would like to. Otherwise I'll fix it in a few days.

**Comment by mikeroyal** [comment]
Okay, made the fix.
