### ISSUE TITLE
OpenNebula and Nomad

### ISSUE THREAD

**Issue by ycadin** [mikeroyal/Self-Hosting-Guide#256]
You could add [OpenNebula](https://opennebula.io) in the Virtualization section.
You could also add [Hashicorp Nomad](https://www.nomadproject.io) in a new Orchestration section or, failing that, in Containers.

Regards

**Comment by mikeroyal** [comment]
Hi @ycadin, feel free to make a Pull Request for this, #257 , and #258.

**Comment by mikeroyal** [comment]
I have add tools to the guide.
