### ISSUE TITLE
Encountered problem when exporting to pdf using vscode

### ISSUE THREAD

**Issue by andersdan** [mikeroyal/Self-Hosting-Guide#274]
The offending line for me was (at line 3644):
**GhostBSD Desktop. Source:[GhostBSD](https://www.ghostbsd.org/)**
Adding a space after "Source:"
**GhostBSD Desktop. Source: [GhostBSD](https://www.ghostbsd.org/)**
seems to have fixed the issue

**Comment by andersdan** [comment]
Closing this one since it seems unimportant. Not sure i did the right thing creating an issue, just wanted to give a heads-up to anyone else getting a error when converting to pdf with vscode plugin.

**Comment by mikeroyal** [comment]
Okay, I fixed that issue thank you for finding it.
