### ISSUE TITLE
DynDNS

### ISSUE THREAD

**Issue by gavinharriss** [mikeroyal/Self-Hosting-Guide#38]
Any good recommendations for dynamic DNS services that can provide a static IP address for self hosters that only have a dynamic DNS provided by their ISP?

BTW, thank you for providing a great guide. I've picked up all sorts of useful resources from it so far :)

**Comment by mikeroyal** [comment]
I would recommend these for self-hosting, though, I know quite a few people use CloudFlare because it does a decent job.

1.  DuckDNS, https://github.com/linuxserver/docker-duckdns or https://www.home-assistant.io/integrations/duckdns/

2. TrustDNS, https://github.com/bluejekyll/trust-dns

**Comment by gavinharriss** [comment]
Thanks Mike, very much appreciated. Numerous options come up when searching but it's always nice to get recommendations off the experts / people that have used them in anger.

**Comment by mikeroyal** [comment]
Cool! Closing this issue now feel to creat eanother if you have any questions/suggestons.

**Comment by TheRealGramdalf** [comment]
Personally I use https://desec.io, they do a great job, one of the best ones imo being that you don't have to renew your domain every thirty days (looking at you, noIP).

I have DynDNS set up on my openwrt router (courtesy of `luci-app-ddns`), and it has a preset for desec as well as a whole bunch of other ones out there. Presets are using `curl` commands, so it's super lightweight as well.
